apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ctf-arena

resources:
  - namespace.yaml
  - configmap.yaml
  - nats.yaml
  - postgres.yaml
  - deployment.yaml
  - worker-deployment.yaml
  - compile-worker-deployment.yaml
  - web-deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: ctf-arena
  app.kubernetes.io/component: api
