apiVersion: v1
kind: Service
metadata:
  name: ctf-api
  namespace: ctf-arena
spec:
  selector:
    app: ctf-api
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
